### ISSUE TITLE
Widget does not work on iOS

### ISSUE THREAD

**Issue by rcha103** [mendix/GeolocationForPhoneGap#2]
Hi, I'm using mendix 7.1.1 and I discovered that the widget does not work at all on iOS. The app asks for location permissions, but the microflow never gets executed. Entity assigned for the longitude and latitude does not change as well.

Edit: I checked the js files to see the issue, and I found out that when calling function _geolocationSuccess, the code 
`this._obj.set(this.latAttr, position.coords.latitude) `
does not get executed and stops. 
Weirdly, this isn't an issue for Android devices.

**Comment by isamu-tanaka** [comment]
It works for iPhone with Mendix 7.11.

**Comment by Andries-Smit** [comment]
Issue seems an old one because the precision of the response is more than 8 digits, which is not supported in Mendix. This now solved by rounding it. https://github.com/mendix/GeolocationForPhoneGap/blob/master/src/GeoLocationForPhoneGap/widget/GeoLocationForPhoneGap.js#L86

If this issue still persists with the latest version of this widget, please open an issue at https://support.mendix.com with an easy reproducible case and step by step instruction to reproduce this issue.

Cheers, Andries
